### ISSUE TITLE
如何在linux环境底下编译这软件？

### ISSUE THREAD

**Issue by ccc1924** [reusee/gotunnel2#1]
提示
common.go:9:2: cannot find package "github.com/nsf/termbox-go" in any of:
        /usr/lib64/go/src/github.com/nsf/termbox-go (from $GOROOT)
        /root/gocode/src/github.com/nsf/termbox-go (from $GOPATH)
如何解决？

**Comment by reusee** [comment]
go get -u github.com/reusee/gotunnel2
